name: Docs

on:
  push:
    paths:
      - '.github/workflows/docs.yaml'
      - 'celina.nim'
      - 'celina/**'
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install deps
      run: |
        nimble install --depsOnly

    - name: Gen docs
      run: |
        nim doc --project --index:on --outdir:./htmldocs -d:asyncBackend=asyncdispatch ./celina.nim

        nim doc --project --index:on --outdir:./htmldocs/widgets ./celina/widgets/base.nim
        nim doc --project --index:on --outdir:./htmldocs/widgets ./celina/widgets/button.nim
        nim doc --project --index:on --outdir:./htmldocs/widgets ./celina/widgets/input.nim
        nim doc --project --index:on --outdir:./htmldocs/widgets ./celina/widgets/list.nim
        nim doc --project --index:on --outdir:./htmldocs/widgets ./celina/widgets/progress.nim
        nim doc --project --index:on --outdir:./htmldocs/widgets ./celina/widgets/table.nim
        nim doc --project --index:on --outdir:./htmldocs/widgets ./celina/widgets/tabs.nim
        nim doc --project --index:on --outdir:./htmldocs/widgets ./celina/widgets/text.nim
        nim doc --project --index:on --outdir:./htmldocs/widgets ./celina/widgets/windows.nim

    - uses: actions/upload-pages-artifact@v4
      with:
        path: ./htmldocs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4
