name: Check `nph` formatting

on:
  pull_request:
    paths:
      - '.github/workflows/nph.yaml'
      - 'celina.nimble'
      - 'src/**'
      - 'tests/**'

jobs:
  nph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check `nph` formatting
        uses: arnetheduck/nph-action@v1
        with:
          version: latest
          options: "src/ tests/ celina.nimble"
          fail: true
          suggest: true
